/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:9d2befe6-d478-4fd8-b130-0520dde02574",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_R2IHzQb3r",
    "aws_user_pools_web_client_id": "2d0gqb2p2m5ovqb6d2edj94hgc",
    "oauth": {},
    "aws_user_files_s3_bucket": "blueprint-coordinates",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
